export const TeamNames = {
    "ARI": "Arizona Diamondbacks",
    "ATL": "Atlanta Braves",
    "BAL": "Baltimore Orioles",
    "BOS": "Boston Red Sox",
    "CHA": "Chicago White Sox",
    "CHN": "Chicago Cubs",
    "CIN": "Cinncinati Reds",
    "COL": "Colorado Rockies",
    "LAN": "Los Angeles Dodgers",
    "NYN": "New York Mets",
    "NYA": "New York Yankees",
    "OAK": "Oakland Athletics",
    "PHI": "Philadelphia Phillies",
    "PIT": "Pittsburgh Pirates",
    "SEA": "Seattle Mariners",
    "WAS": "Washington Nationals",
}